# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec86302be6039757887e0194c58c3ddc3c60d4ce2a6eb29ef1a7516f948e2ebfac710ea42c749288e363f373feede1fb454ee2a728ad7118ca0b6d9bbd1aec12
  google_client_audience: <%= ENV["GOOGLE_CLIENT_AUDIENCE"] %>
  google_client_audience_web: <%= ENV["GOOGLE_CLIENT_AUDIENCE_WEB"] %>
  google_maps_key: <%= ENV["GOOGLE_MAPS_KEY"] %>

test:
  secret_key_base: b300c2b3a4a6b02d94e5ab3e71ca0c99528d210e6b486194b5d7bd83636fbdd30dc919b9b836a68215fa9366cfec29f5bc4bb009ddda4a195fb87e6611df7435

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_client_audience: <%= ENV["GOOGLE_CLIENT_AUDIENCE"] %>
  google_client_audience_web: <%= ENV["GOOGLE_CLIENT_AUDIENCE_WEB"] %>
  google_maps_key: <%= ENV["GOOGLE_MAPS_KEY"] %>
